import { MenuSelectItemType } from "@/app/common/components/filters/types";
import { BreadcrumbType } from "@/app/common/types/breadcrumb.type";
import { FilterType, ProductType } from "@/components/products/types";
import {
  Img1,
  Img2,
  Img3,
  Img4,
  Img5,
  Img6,
  Img7,
  Img8,
  Img9,
} from "@/assets/images/products/utils";
import { TableHeaderType } from "@/app/common/types/table.types";
import { OptionType } from "@/app/common/types/option.type";

export const productBreadcrumb: BreadcrumbType[] = [
  {
    title: "home",
    disabled: false,
  },
  {
    title: "site",
    disabled: true,
  },
];

export const filter: FilterType = {
  query: "",
  brands: [],
  category: "",
  discount: "",
};

export const brandOptions: MenuSelectItemType[] = [
  { value: "boat", label: "Boat" },
  { value: "puma", label: "Puma" },
  { value: "adidas", label: "Adidas" },
  { value: "realMe", label: "RealMe" },
];

export const categoryOptions: MenuSelectItemType[] = [
  { value: "Appliances", label: "Appliances" },
  { value: "Automotive Accessories", label: "Automotive Accessories" },
  { value: "Electronics", label: "Electronics" },
  { value: "Fashion", label: "Fashion" },
  { value: "Furniture", label: "Furniture" },
  { value: "Grocery", label: "Grocery" },
  { value: "Headphones", label: "Headphones" },
  { value: "Kids", label: "Kids" },
  { value: "Luggage", label: "Luggage" },
  { value: "Sports", label: "Sports" },
  { value: "Watches", label: "Watches" },
];

export const discountOptions: MenuSelectItemType[] = [
  { value: "50$", label: "50% or more" },
  { value: "40%", label: "40% or more" },
  { value: "30%", label: "30% or more" },
  { value: "20%", label: "20% or more" },
  { value: "10%", label: "10% or more" },
  { value: "0%", label: "Less than 10%" },
];

export const productsHeader: TableHeaderType[] = [
  { title: "all", isCheck: true },
  { title: "Products" },
  { title: "Category" },
  { title: "Stock" },
  { title: "Price" },
  { title: "Orders" },
  { title: "Rating" },
  { title: "Publish" },
  { title: "Action" },
];

export const products: ProductType[] = [
  {
    id: 1,
    img: [Img1],
    img_alt: "img-1.png",
    title: "Cotton collar tshirts for men",
    category: "Fashion",
    stock: "12",
    price: "215.00",
    discount: "25%",
    orders: "06",
    ratings: "4.9",
    publish: "12 Oct, 2022",
  },
  {
    id: 2,
    img: [Img2],
    img_alt: "img-2.png",
    title: "Like style travel black handbag",
    category: "Luggage",
    stock: "06",
    price: "160.00",
    discount: "0%",
    orders: "02",
    ratings: "4.3",
    publish: "06 Jan, 2023",
  },
  {
    id: 3,
    img: [Img3],
    img_alt: "img-3.png",
    title: "Fossil Gen 5E Smart Watch",
    category: "Watches",
    stock: "19",
    price: "120.00",
    discount: "42%",
    orders: "21",
    ratings: "4.3",
    publish: "26 Mar, 2021",
  },
  {
    id: 4,
    img: [Img4],
    img_alt: "img-4.png",
    title: "Super Bass Blutooth wireless headphone",
    category: "Headphones",
    stock: "23",
    price: "180.00",
    discount: "0%",
    orders: "19",
    ratings: "4.1",
    publish: "19 Apr, 2021",
  },
  {
    id: 5,
    img: [Img5],
    img_alt: "img-5.png",
    title: "Willage Volleyball Ball Size 4",
    category: "Sports",
    stock: "30",
    price: "99.00",
    discount: "10%",
    orders: "21",
    ratings: "4.0",
    publish: "30 Mar, 2021",
  },
  {
    id: 6,
    img: [Img6],
    img_alt: "img-6.png",
    title: "Blive Printed Men Round Neck",
    category: "Fashion",
    stock: "35",
    price: "250.00",
    discount: "0%",
    orders: "02",
    ratings: "3.8",
    publish: "12 Oct, 2021",
  },
  {
    id: 7,
    img: [Img7],
    img_alt: "img-7.png",
    title: "Cotton collar tshirts for men",
    category: "Fashion",
    stock: "12",
    price: "180.00",
    discount: "0%",
    orders: "10",
    ratings: "4.0",
    publish: "15 May, 2021",
  },
  {
    id: 8,
    img: [Img8],
    img_alt: "img-8.png",
    title: "Full Sleeve Solid Men Sweatshirt/Hoody",
    category: "Fashion",
    stock: "20",
    price: "260.00",
    discount: "12%",
    orders: "20",
    ratings: "4.1",
    publish: "21 Jun, 2021",
  },
  {
    id: 9,
    img: [Img1],
    img_alt: "img-10.png",
    title: "Men's Round Neck Half Sleeves Solid T-Shirt",
    category: "Fashion",
    stock: "21",
    price: "160.00",
    discount: "0%",
    orders: "08",
    ratings: "4.4",
    publish: "15 Jan, 2021",
  },
  {
    id: 10,
    img: [Img9],
    img_alt: "img-9.png",
    title: "Flip-Flops and House Slippers",
    category: "Footwear",
    stock: "30",
    price: "150.00",
    discount: "0%",
    orders: "10",
    ratings: "4.2",
    publish: "06 Jan, 2023",
  },
  {
    id: 11,
    img: [Img1],
    img_alt: "img-11.png",
    title: "Jeans blue men boxer",
    category: "Fashion",
    stock: "50",
    price: "97.99",
    discount: "25%",
    orders: "51",
    ratings: "3.9",
    publish: "12 Oct, 2021",
  },
  {
    id: 12,
    img: [Img1],
    img_alt: "img-12.png",
    title: "MAG back to the future shoes",
    category: "Footwear",
    stock: "06",
    price: "274.99",
    discount: "0%",
    orders: "06",
    ratings: "4.2",
    publish: "06 Jan, 2021",
  },
  {
    id: 13,
    img: [Img4],
    img_alt: "img-4.png",
    title: "Super Bass Blutooth wireless headphone",
    category: "Headphones",
    stock: "23",
    price: "180.00",
    discount: "0%",
    orders: "19",
    ratings: "4.1",
    publish: "19 Apr, 2021",
  },
  {
    id: 14,
    img: [Img7],
    img_alt: "img-7.png",
    title: "Cotton collar tshirts for men",
    category: "Fashion",
    stock: "12",
    price: "180.00",
    discount: "0%",
    orders: "10",
    ratings: "4.0",
    publish: "15 May, 2021",
  },
];

export const productAction: OptionType[] = [
  {
    title: "View",
    icon: "ph-eye",
    value: "view",
    to: "/ecommerce/product-details",
  },
  {
    title: "Edit",
    icon: "ph-pencil",
    value: "edit",
  },
  {
    title: "Remove",
    icon: "ph-trash",
    value: "remove",
  },
];
