version: '3'
services:
#  bsites-ui:
#    container_name: bsites-ui
#    image: bsites-ui:latest
#    ports:
#      - '3000:80'
#    environment:
#      - BASE_API_URL=http://bsites-api:4000
#    networks:
#      - bsitesapi
#    restart: always
#    stdin_open: true
#    tty: true
  bsites-api:
    container_name: bsites-api
    image: bsites-api:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - mongo
      - redis
    command: npm run start:dev
    ports:
      - '4001:4000'
#      - '9229:9229'
    networks:
      - bsitesapi
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
  mongo:
    image: mongo:4.4
    container_name: bsites-mongo
    restart: always
    ports:
      - '28017:27017'
    environment:
      MONGO_INITDB_DATABASE: '${DATABASE}'
      MONGO_INITDB_ROOT_USERNAME: '${DATABASE_USER}'
      MONGO_INITDB_ROOT_PASSWORD: '${DATABASE_PASSWORD}'
    volumes:
      - bsitesmongo:/data/db
    networks:
      - bsitesapi
  redis:
    image: redis:alpine
    container_name: bsites-redis
    ports:
      - '6389:${REDIS_PORT_LOCAL}'
    volumes:
      - bsitesredis:/data
    networks:
      - bsitesapi
networks:
  bsitesapi:
    driver: 'bridge'
volumes:
  bsitesredis:
    driver: 'local'
  bsitesmongo:
    driver: 'local'
